
package formulario;

/**
 *
 * @author Juan Farias 
 */

public class Cadastrar extends javax.swing.JFrame {
    
    String nome, endereco, bairro, cidade, estado, cep, sexo, celular, telefone, aniversario, dataCadastro;
    String codigoCliente;
    /**
     * Creates new form Cadastro
     */
    public Cadastrar() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel5 = new javax.swing.JLabel();
        buttonGroup1 = new javax.swing.ButtonGroup();
        jRadioButton3 = new javax.swing.JRadioButton();
        jProgressBar1 = new javax.swing.JProgressBar();
        jSlider1 = new javax.swing.JSlider();
        jTextField6 = new javax.swing.JTextField();
        jComboBox1 = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        LblCodigo = new javax.swing.JLabel();
        LblNome = new javax.swing.JLabel();
        LblEndereco = new javax.swing.JLabel();
        LblBairro = new javax.swing.JLabel();
        LblCidade = new javax.swing.JLabel();
        LblEstado = new javax.swing.JLabel();
        LblCEP = new javax.swing.JLabel();
        LblSexo = new javax.swing.JLabel();
        LblCel = new javax.swing.JLabel();
        LblTel = new javax.swing.JLabel();
        LblNiver = new javax.swing.JLabel();
        LblCad = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        TCodigo = new javax.swing.JTextField();
        TNome = new javax.swing.JTextField();
        TEnd = new javax.swing.JTextField();
        CboEst = new javax.swing.JComboBox<>();
        TBairro = new javax.swing.JTextField();
        TCidade = new javax.swing.JTextField();
        RFeminino = new javax.swing.JRadioButton();
        RMasculino = new javax.swing.JRadioButton();
        TCel = new javax.swing.JTextField();
        TTel = new javax.swing.JTextField();
        TNiver = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        BtnCadastrar = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        TCad = new javax.swing.JTextField();
        TCEP = new javax.swing.JTextField();

        jLabel5.setText("jLabel5");

        jRadioButton3.setText("jRadioButton3");

        jTextField6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField6ActionPerformed(evt);
            }
        });

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setPreferredSize(new java.awt.Dimension(593, 469));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        LblCodigo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        LblCodigo.setText("Código do cliente");
        jPanel2.add(LblCodigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 9, 238, -1));

        LblNome.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        LblNome.setText("Nome completo");
        jPanel2.add(LblNome, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 38, 238, -1));

        LblEndereco.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        LblEndereco.setText("Endereço");
        jPanel2.add(LblEndereco, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 67, 238, -1));

        LblBairro.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        LblBairro.setText("Bairro");
        jPanel2.add(LblBairro, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 96, 238, -1));

        LblCidade.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        LblCidade.setText("Cidade");
        jPanel2.add(LblCidade, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 125, 238, -1));

        LblEstado.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        LblEstado.setText("Estado");
        jPanel2.add(LblEstado, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 154, 238, -1));

        LblCEP.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        LblCEP.setText("CEP");
        jPanel2.add(LblCEP, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 183, 238, -1));

        LblSexo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        LblSexo.setText("Sexo");
        jPanel2.add(LblSexo, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 211, 238, -1));

        LblCel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        LblCel.setText("Celular");
        jPanel2.add(LblCel, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 239, 238, -1));

        LblTel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        LblTel.setText("Telefone");
        jPanel2.add(LblTel, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 268, 238, -1));

        LblNiver.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        LblNiver.setText("Data de aniversário");
        jPanel2.add(LblNiver, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 297, 238, -1));

        LblCad.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        LblCad.setText("Data de cadastro");
        jPanel2.add(LblCad, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 326, 238, -1));

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(499, 6, 338, -1));

        TCodigo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        TCodigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TCodigoActionPerformed(evt);
            }
        });
        jPanel2.add(TCodigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 6, 243, -1));

        TNome.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        TNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TNomeActionPerformed(evt);
            }
        });
        jPanel2.add(TNome, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 35, 243, -1));

        TEnd.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jPanel2.add(TEnd, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 64, 243, -1));

        CboEst.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        CboEst.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Estado", "SP", "RJ", "BH", "AL", "AC", "SC" }));
        CboEst.setToolTipText("");
        jPanel2.add(CboEst, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 151, 243, -1));

        TBairro.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jPanel2.add(TBairro, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 93, 243, -1));

        TCidade.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jPanel2.add(TCidade, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 122, 243, -1));

        RFeminino.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        RFeminino.setText("Feminino");
        jPanel2.add(RFeminino, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 209, -1, -1));

        RMasculino.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        RMasculino.setText("Masculino");
        jPanel2.add(RMasculino, new org.netbeans.lib.awtextra.AbsoluteConstraints(345, 209, -1, -1));

        TCel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jPanel2.add(TCel, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 236, 243, -1));

        TTel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jPanel2.add(TTel, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 265, 243, -1));

        TNiver.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jPanel2.add(TNiver, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 294, 243, -1));

        BtnCadastrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/formulario/support-man.png"))); // NOI18N
        BtnCadastrar.setText("Cadastrar");
        BtnCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnCadastrarActionPerformed(evt);
            }
        });

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/formulario/63602305968.png"))); // NOI18N
        jButton1.setText("Limpar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/formulario/Back (2).png"))); // NOI18N
        jButton3.setText("Fechar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(BtnCadastrar, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(25, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(BtnCadastrar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(36, 36, 36))
        );

        jPanel2.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(18, 364, -1, 59));

        TCad.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jPanel2.add(TCad, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 323, 243, -1));

        TCEP.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jPanel2.add(TCEP, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 180, 243, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(345, 345, 345)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addContainerGap(161, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addContainerGap(415, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 445, Short.MAX_VALUE)
                    .addContainerGap()))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField6ActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void BtnCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnCadastrarActionPerformed

      
        codigoCliente= TCodigo.getText();
        nome= TNome.getText();
        endereco = TEnd.getText();
        bairro = TBairro.getText();
        cidade = TCidade.getText();
        estado = (String)CboEst.getSelectedItem();
        cep = TCEP.getText();
        celular = TCel.getText();
        telefone = TTel.getText();
        aniversario = TNiver.getText();
        dataCadastro = TCad.getText();
        
        // cadastrar o sexo do usuario
        
        if(RFeminino.isSelected()){
        sexo = "Feminino";
        buttonGroup1.clearSelection();
        }else if(RMasculino.isSelected()){
        sexo = "Masculino";
        }

       Exibir entrar = new Exibir();
        entrar.setVisible(true);

        entrar.ResultCod.setText(codigoCliente);
        entrar.ResultNome.setText(nome);
        entrar.ResultEnd.setText(endereco);
        entrar.ResultBairro.setText(bairro);
        entrar.ResultEst.setText(estado);
        entrar.ResultCid.setText(cidade);
        entrar.ResultCep.setText(cep);
        entrar.ResultSexo.setText(sexo);
        entrar.ResultCel.setText(celular);
        entrar.ResultTel.setText(telefone);
        entrar.ResultNiver.setText(aniversario);
        entrar.ResultDataCad.setText(dataCadastro);
        dispose();
    }//GEN-LAST:event_BtnCadastrarActionPerformed

    
    
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        TCodigo.setText("");
        TNome.setText("");
        TEnd.setText("");
        TBairro.setText("");
        TCidade.setText("");
        TCEP.setText("");
        TCel.setText("");
        TTel.setText("");
        TNiver.setText("");
        TCad.setText("");
        buttonGroup1.clearSelection();
        CboEst.setSelectedIndex(0);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void TNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TNomeActionPerformed

    private void TCodigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TCodigoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TCodigoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Cadastrar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Cadastrar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Cadastrar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Cadastrar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Cadastrar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton BtnCadastrar;
    public javax.swing.JComboBox<String> CboEst;
    private javax.swing.JLabel LblBairro;
    private javax.swing.JLabel LblCEP;
    private javax.swing.JLabel LblCad;
    private javax.swing.JLabel LblCel;
    private javax.swing.JLabel LblCidade;
    private javax.swing.JLabel LblCodigo;
    private javax.swing.JLabel LblEndereco;
    private javax.swing.JLabel LblEstado;
    private javax.swing.JLabel LblNiver;
    private javax.swing.JLabel LblNome;
    private javax.swing.JLabel LblSexo;
    private javax.swing.JLabel LblTel;
    public javax.swing.JRadioButton RFeminino;
    public javax.swing.JRadioButton RMasculino;
    public javax.swing.JTextField TBairro;
    public javax.swing.JTextField TCEP;
    public javax.swing.JTextField TCad;
    public javax.swing.JTextField TCel;
    public javax.swing.JTextField TCidade;
    public javax.swing.JTextField TCodigo;
    public javax.swing.JTextField TEnd;
    public javax.swing.JTextField TNiver;
    public javax.swing.JTextField TNome;
    public javax.swing.JTextField TTel;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JProgressBar jProgressBar1;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSlider jSlider1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextField6;
    // End of variables declaration//GEN-END:variables
}
