/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package formulario;

/**
 *
 * @author FATEC ZONA LESTE
 */
public class Exibir extends javax.swing.JFrame {

    /**
     * Creates new form Informacoes
     */
    public Exibir() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField11 = new javax.swing.JTextField();
        jTextField10 = new javax.swing.JTextField();
        jTextField9 = new javax.swing.JTextField();
        jTextField8 = new javax.swing.JTextField();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jTextField7 = new javax.swing.JTextField();
        jComboBox2 = new javax.swing.JComboBox<>();
        jTextField5 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField1 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        ResultEst = new javax.swing.JLabel();
        ResultCep = new javax.swing.JLabel();
        LblEndereco = new javax.swing.JLabel();
        ResultSexo = new javax.swing.JLabel();
        LblBairro = new javax.swing.JLabel();
        ResultCel = new javax.swing.JLabel();
        LblCidade = new javax.swing.JLabel();
        ResultTel = new javax.swing.JLabel();
        LblEstado = new javax.swing.JLabel();
        ResultNiver = new javax.swing.JLabel();
        LblCEP = new javax.swing.JLabel();
        ResultDataCad = new javax.swing.JLabel();
        LblSexo = new javax.swing.JLabel();
        LblCel = new javax.swing.JLabel();
        LblTel = new javax.swing.JLabel();
        LblNiver = new javax.swing.JLabel();
        LblCad = new javax.swing.JLabel();
        ResultCod = new javax.swing.JLabel();
        ResultNome = new javax.swing.JLabel();
        ResultEnd = new javax.swing.JLabel();
        ResultBairro = new javax.swing.JLabel();
        ResultCid = new javax.swing.JLabel();
        LblCodigo = new javax.swing.JLabel();
        LblNome = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        LblCodigo1 = new javax.swing.JLabel();

        jTextField9.setText("(xx)");

        jTextField8.setText("(xx)");

        jRadioButton1.setText("Feminino");

        jRadioButton2.setText("Masculino");

        jTextField7.setText(" ");

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Estado", "SP", "RJ", "RS", "MA", "PA", "AC" }));
        jComboBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox2ActionPerformed(evt);
            }
        });

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(199, 57, -1, -1));
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(217, 57, -1, -1));

        ResultEst.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        ResultEst.setText(" ");
        getContentPane().add(ResultEst, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 182, -1, -1));

        ResultCep.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        ResultCep.setText(" ");
        getContentPane().add(ResultCep, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 205, -1, -1));

        LblEndereco.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        LblEndereco.setText("Endereço:");
        getContentPane().add(LblEndereco, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 113, 238, -1));

        ResultSexo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        ResultSexo.setText(" ");
        getContentPane().add(ResultSexo, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 228, -1, -1));

        LblBairro.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        LblBairro.setText("Bairro:");
        getContentPane().add(LblBairro, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 136, 238, -1));

        ResultCel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        ResultCel.setText(" ");
        getContentPane().add(ResultCel, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 251, -1, -1));

        LblCidade.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        LblCidade.setText("Cidade:");
        getContentPane().add(LblCidade, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 159, 238, -1));

        ResultTel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        ResultTel.setText(" ");
        getContentPane().add(ResultTel, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 274, -1, -1));

        LblEstado.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        LblEstado.setText("Estado:");
        getContentPane().add(LblEstado, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 182, 238, -1));

        ResultNiver.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        ResultNiver.setText(" ");
        getContentPane().add(ResultNiver, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 297, -1, -1));

        LblCEP.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        LblCEP.setText("CEP:");
        getContentPane().add(LblCEP, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 205, 238, -1));

        ResultDataCad.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        ResultDataCad.setText(" ");
        getContentPane().add(ResultDataCad, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 320, -1, -1));

        LblSexo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        LblSexo.setText("Sexo:");
        getContentPane().add(LblSexo, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 228, 238, -1));

        LblCel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        LblCel.setText("Celular:");
        getContentPane().add(LblCel, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 251, 238, -1));

        LblTel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        LblTel.setText("Telefone:");
        getContentPane().add(LblTel, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 274, 238, -1));

        LblNiver.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        LblNiver.setText("Data de aniversário:");
        getContentPane().add(LblNiver, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 297, 238, -1));

        LblCad.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        LblCad.setText("Data de cadastro:");
        getContentPane().add(LblCad, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 320, 238, -1));

        ResultCod.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        ResultCod.setText(" ");
        getContentPane().add(ResultCod, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 67, -1, -1));

        ResultNome.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        ResultNome.setText(" ");
        getContentPane().add(ResultNome, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 90, -1, -1));

        ResultEnd.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        ResultEnd.setText(" ");
        getContentPane().add(ResultEnd, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 113, -1, -1));

        ResultBairro.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        ResultBairro.setText(" ");
        getContentPane().add(ResultBairro, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 136, 180, -1));

        ResultCid.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        ResultCid.setText(" ");
        getContentPane().add(ResultCid, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 159, -1, -1));

        LblCodigo.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        LblCodigo.setText("CADASTRADO");
        getContentPane().add(LblCodigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 10, 180, -1));

        LblNome.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        LblNome.setText("Nome completo:");
        getContentPane().add(LblNome, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 90, 238, -1));

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/formulario/Erase.png"))); // NOI18N
        jButton3.setText("Fechar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 360, 380, -1));

        LblCodigo1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        LblCodigo1.setText("Código do cliente:");
        getContentPane().add(LblCodigo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 67, 238, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jComboBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Exibir.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Exibir.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Exibir.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Exibir.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Exibir().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LblBairro;
    private javax.swing.JLabel LblCEP;
    private javax.swing.JLabel LblCad;
    private javax.swing.JLabel LblCel;
    private javax.swing.JLabel LblCidade;
    private javax.swing.JLabel LblCodigo;
    private javax.swing.JLabel LblCodigo1;
    private javax.swing.JLabel LblEndereco;
    private javax.swing.JLabel LblEstado;
    private javax.swing.JLabel LblNiver;
    private javax.swing.JLabel LblNome;
    private javax.swing.JLabel LblSexo;
    private javax.swing.JLabel LblTel;
    public javax.swing.JLabel ResultBairro;
    public javax.swing.JLabel ResultCel;
    public javax.swing.JLabel ResultCep;
    public javax.swing.JLabel ResultCid;
    public javax.swing.JLabel ResultCod;
    public javax.swing.JLabel ResultDataCad;
    public javax.swing.JLabel ResultEnd;
    public javax.swing.JLabel ResultEst;
    public javax.swing.JLabel ResultNiver;
    public javax.swing.JLabel ResultNome;
    public javax.swing.JLabel ResultSexo;
    public javax.swing.JLabel ResultTel;
    private javax.swing.JButton jButton3;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JTextField jTextField11;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    // End of variables declaration//GEN-END:variables
}
